name: Close Stale Issues

on:
  schedule:
    - cron: '30 1 * * *'

permissions:
  contents: read

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@3b876b2c9617e3b5d3779d42cded2e6e46c871e0 # v9.1.0
        with:
          only-issues: true
          days-before-stale: 60
          days-before-close: 14
          days-before-pr-stale: -1
          days-before-pr-close: -1
          stale-issue-message: 'This issue is stale because it has been open 60 days with no activity. Remove the "stale" label or comment, or it will be closed in 14 days.'
          close-issue-message: 'This issue was closed because it has been stalled for 14 days with no activity.'
          stale-issue-label: 'stale'
          exempt-issue-labels: 'pinned,security,epic'